[GLOBAL]
pants_version = "2.3.1"
backend_packages = ["pants.backend.python"]

[python-setup]
resolver_version = "pip-2020-resolver"
interpreter_constraints = ["==3.8.12"]

[source]
root_patterns = [
  'src',
  'tests',
]
