python_library()

pex_binary(
    name="image-preprocess",
    entry_point="vector.py",
)

pex_binary(
    name="list-download",
    entry_point="list.py",
)

pex_binary(
    name="image-download",
    entry_point="image.py",
)