AWSTemplateFormatVersion: 2010-09-09
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lookalike-manual
  ImageBucketPublicAccess:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${ImageBucket}/*/0.jpg
            Principal: "*"
