AWSTemplateFormatVersion: 2010-09-09
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lookalike-manual
  ImageBucketPublicAccess:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${ImageBucket}/*/0.jpg
            Principal: "*"
  ScrapeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: lookalike-extraction-queue
      MaximumMessageSize: 1024
      MessageRetentionPeriod: 1058400 # 7 days
      ReceiveMessageWaitTimeSeconds: 20 # enable long polling
